name: Python Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        pip install pytest
        # Running these tests separately to avoid file name clashes
        pytest -v leetcode/*.py
        pytest -v google/*.py
        pytest -v cs212/test_*.py
        pytest -v daily-interview/*.py
